/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AppAchievementsRouteImport } from './routes/_app.achievements'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppCertificationsRouteImport } from './routes/_app.certifications'
import { Route as AppCustomerServiceRouteImport } from './routes/_app.customer-service'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppScheduleRouteImport } from './routes/_app.schedule'
import { Route as AppSecurityRouteImport } from './routes/_app.security'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTutorialsRouteImport } from './routes/_app.tutorials'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteContactUsRouteImport } from './routes/_site.contact-us'
import { Route as SiteFeaturesRouteImport } from './routes/_site.features'
import { Route as SitePricingRouteImport } from './routes/_site.pricing'
import { Route as SiteAuthCallbackRouteImport } from './routes/_site.auth.callback'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificationsRoute = AppCertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomerServiceRoute = AppCustomerServiceRouteImport.update({
  id: '/customer-service',
  path: '/customer-service',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTutorialsRoute = AppTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactUsRoute = SiteContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFeaturesRoute = SiteFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAuthCallbackRoute = SiteAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/achievements': typeof AppAchievementsRoute
  '/billing': typeof AppBillingRoute
  '/certifications': typeof AppCertificationsRoute
  '/customer-service': typeof AppCustomerServiceRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/schedule': typeof AppScheduleRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/tutorials': typeof AppTutorialsRoute
  '/wallet': typeof AppWalletRoute
  '/about': typeof SiteAboutRoute
  '/contact-us': typeof SiteContactUsRoute
  '/features': typeof SiteFeaturesRoute
  '/pricing': typeof SitePricingRoute
  '/auth/callback': typeof SiteAuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/achievements': typeof AppAchievementsRoute
  '/billing': typeof AppBillingRoute
  '/certifications': typeof AppCertificationsRoute
  '/customer-service': typeof AppCustomerServiceRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/schedule': typeof AppScheduleRoute
  '/security': typeof AppSecurityRoute
  '/settings': typeof AppSettingsRoute
  '/tutorials': typeof AppTutorialsRoute
  '/wallet': typeof AppWalletRoute
  '/about': typeof SiteAboutRoute
  '/contact-us': typeof SiteContactUsRoute
  '/features': typeof SiteFeaturesRoute
  '/pricing': typeof SitePricingRoute
  '/auth/callback': typeof SiteAuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/certifications': typeof AppCertificationsRoute
  '/_app/customer-service': typeof AppCustomerServiceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tutorials': typeof AppTutorialsRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact-us': typeof SiteContactUsRoute
  '/_site/features': typeof SiteFeaturesRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/auth/callback': typeof SiteAuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/billing'
    | '/certifications'
    | '/customer-service'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/schedule'
    | '/security'
    | '/settings'
    | '/tutorials'
    | '/wallet'
    | '/about'
    | '/contact-us'
    | '/features'
    | '/pricing'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/billing'
    | '/certifications'
    | '/customer-service'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/schedule'
    | '/security'
    | '/settings'
    | '/tutorials'
    | '/wallet'
    | '/about'
    | '/contact-us'
    | '/features'
    | '/pricing'
    | '/auth/callback'
  id:
    | '__root__'
    | '/_app'
    | '/_site'
    | '/_app/achievements'
    | '/_app/billing'
    | '/_app/certifications'
    | '/_app/customer-service'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/schedule'
    | '/_app/security'
    | '/_app/settings'
    | '/_app/tutorials'
    | '/_app/wallet'
    | '/_site/about'
    | '/_site/contact-us'
    | '/_site/features'
    | '/_site/pricing'
    | '/_site/'
    | '/_site/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/certifications': {
      id: '/_app/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof AppCertificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customer-service': {
      id: '/_app/customer-service'
      path: '/customer-service'
      fullPath: '/customer-service'
      preLoaderRoute: typeof AppCustomerServiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tutorials': {
      id: '/_app/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof AppTutorialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact-us': {
      id: '/_site/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof SiteContactUsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/features': {
      id: '/_site/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof SiteFeaturesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/auth/callback': {
      id: '/_site/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof SiteAuthCallbackRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCertificationsRoute: typeof AppCertificationsRoute
  AppCustomerServiceRoute: typeof AppCustomerServiceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTutorialsRoute: typeof AppTutorialsRoute
  AppWalletRoute: typeof AppWalletRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppBillingRoute: AppBillingRoute,
  AppCertificationsRoute: AppCertificationsRoute,
  AppCustomerServiceRoute: AppCustomerServiceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTutorialsRoute: AppTutorialsRoute,
  AppWalletRoute: AppWalletRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactUsRoute: typeof SiteContactUsRoute
  SiteFeaturesRoute: typeof SiteFeaturesRoute
  SitePricingRoute: typeof SitePricingRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteAuthCallbackRoute: typeof SiteAuthCallbackRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactUsRoute: SiteContactUsRoute,
  SiteFeaturesRoute: SiteFeaturesRoute,
  SitePricingRoute: SitePricingRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteAuthCallbackRoute: SiteAuthCallbackRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
