/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteFeaturesRouteImport } from './routes/_site.features'
import { Route as SitePricingRouteImport } from './routes/_site.pricing'
import { Route as SiteAuthCallbackRouteImport } from './routes/_site.auth.callback'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFeaturesRoute = SiteFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAuthCallbackRoute = SiteAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/dashboard': typeof DashboardRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/features': typeof SiteFeaturesRoute
  '/pricing': typeof SitePricingRoute
  '/auth/callback': typeof SiteAuthCallbackRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/features': typeof SiteFeaturesRoute
  '/pricing': typeof SitePricingRoute
  '/': typeof SiteIndexRoute
  '/auth/callback': typeof SiteAuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/features': typeof SiteFeaturesRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/auth/callback': typeof SiteAuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/about'
    | '/contact'
    | '/features'
    | '/pricing'
    | '/'
    | '/auth/callback'
  id:
    | '__root__'
    | '/_site'
    | '/dashboard'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/features'
    | '/_site/pricing'
    | '/_site/'
    | '/_site/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/features': {
      id: '/_site/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof SiteFeaturesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/auth/callback': {
      id: '/_site/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof SiteAuthCallbackRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteFeaturesRoute: typeof SiteFeaturesRoute
  SitePricingRoute: typeof SitePricingRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteAuthCallbackRoute: typeof SiteAuthCallbackRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteFeaturesRoute: SiteFeaturesRoute,
  SitePricingRoute: SitePricingRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteAuthCallbackRoute: SiteAuthCallbackRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  DashboardRoute: DashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
